apiVersion: v1
kind: Pod
metadata:
  name: httpserver
spec:
  terminationGracePeriodSeconds: 60
  containers:
    - name: httpserver
      image: lin445122/httpserver:v2
      command: ["/bin/sh"]
      args: ["-c", "while true; do echo hello; sleep 10;done"]
